name: learn_github_action
on:
  push:
    branches:
      - 'test**'

jobs:
  tag_story_with_fix_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions
